//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rango.Common.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rango.Common.Resources.Errors.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an address.
        /// </summary>
        public static string AddressEmpty {
            get {
                return ResourceManager.GetString("AddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a code country.
        /// </summary>
        public static string CodeStateTelephone {
            get {
                return ResourceManager.GetString("CodeStateTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment must not exceed 500 characters.
        /// </summary>
        public static string CommentaryInvalid {
            get {
                return ResourceManager.GetString("CommentaryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the Culinary.
        /// </summary>
        public static string CulinaryInvalid {
            get {
                return ResourceManager.GetString("CulinaryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a DDI.
        /// </summary>
        public static string DDITelephone {
            get {
                return ResourceManager.GetString("DDITelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials Invalid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Image Card Url.
        /// </summary>
        public static string ImageCardUrlInvalid {
            get {
                return ResourceManager.GetString("ImageCardUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Invalid.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password confirmation.
        /// </summary>
        public static string InvalidPasswordConfirmation {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reference site of your establishment.
        /// </summary>
        public static string NetworkNameInvalid {
            get {
                return ResourceManager.GetString("NetworkNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string NomeInvalid {
            get {
                return ResourceManager.GetString("NomeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number is invalid.
        /// </summary>
        public static string NumberTelephone {
            get {
                return ResourceManager.GetString("NumberTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Order.
        /// </summary>
        public static string OrderInvalid {
            get {
                return ResourceManager.GetString("OrderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 to 20 characters.
        /// </summary>
        public static string PasswordIntervalCaractere {
            get {
                return ResourceManager.GetString("PasswordIntervalCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Payment method name.
        /// </summary>
        public static string PaymentMethodNameInvalid {
            get {
                return ResourceManager.GetString("PaymentMethodNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Product.
        /// </summary>
        public static string ProductInvalid {
            get {
                return ResourceManager.GetString("ProductInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be greater than zero.
        /// </summary>
        public static string QuantityInvalid {
            get {
                return ResourceManager.GetString("QuantityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informed value must be from 0 to 5.
        /// </summary>
        public static string RangeNumeric {
            get {
                return ResourceManager.GetString("RangeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the category.
        /// </summary>
        public static string TitleInvalid {
            get {
                return ResourceManager.GetString("TitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Page Url.
        /// </summary>
        public static string UrlPageInvalid {
            get {
                return ResourceManager.GetString("UrlPageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a User.
        /// </summary>
        public static string UserEmpty {
            get {
                return ResourceManager.GetString("UserEmpty", resourceCulture);
            }
        }
    }
}
